"""Paper-style figures from benchmark CSVs and a fresh core solve (Figure 3).

Section 4 of ``paper.pdf`` shows:
  - Figure 1: European call price / delta errors vs spot (legacy Hyndman & Oyono Ngou 2017 style).
  - Figure 2: same panels for the new boundary-control scheme.
  - Figure 3: delta surface in (time, spot) for the new scheme.

Figures 1--2 are drawn from a full-spot benchmark CSV (default: under
``implementation_version_0/results/``).
Figure 3 is generated by re-running ``solve_core`` on the log-price grid (not stored in the CSV).
"""

from __future__ import annotations

import argparse
import csv
import math
import sys
from collections import defaultdict
from pathlib import Path

from bsde_cfft_app.paths import RESULTS_DIR


def _load_surface_rows(path: Path) -> dict[str, list[dict[str, str]]]:
    by_method: dict[str, list[dict[str, str]]] = defaultdict(list)
    with path.open(newline="", encoding="utf-8") as handle:
        for row in csv.DictReader(handle):
            by_method[row["method"]].append(row)
    for rows in by_method.values():
        rows.sort(key=lambda r: float(r["spot_eval"]))
    return by_method


def _plot_price_delta_vs_spot(
    *,
    rows: list[dict[str, str]],
    title: str,
    outfile: Path,
) -> None:
    import matplotlib.pyplot as plt

    spots = [float(r["spot_eval"]) for r in rows]
    pe = [float(r["abs_price_err"]) for r in rows]
    de = [float(r["abs_delta_z_err"]) for r in rows]

    fig, axes = plt.subplots(2, 1, figsize=(9.0, 6.5), sharex=True)
    fig.suptitle(title, fontsize=12)

    axes[0].plot(spots, pe, color="C0", linewidth=1.6)
    axes[0].set_ylabel("|price error|")
    axes[0].grid(True, alpha=0.35)

    axes[1].plot(spots, de, color="C3", linewidth=1.6)
    axes[1].set_ylabel("|delta error|  (Z-based)")
    axes[1].set_xlabel("spot S")
    axes[1].grid(True, alpha=0.35)

    fig.tight_layout()
    fig.savefig(outfile, dpi=150)
    plt.close(fig)


def _plot_delta_surface(
    *,
    outfile: Path,
    spot: float,
    strike: float,
    rate: float,
    sigma: float,
    maturity: float,
    n_time_steps: int,
    truncation_length: float,
    n_space_points: int,
    damping_alpha: float,
) -> None:
    import matplotlib.pyplot as plt
    import numpy as np

    from implementation_version_0.cfft.core_algorithm import CoreConfig, CoreInputs, solve_core

    config = CoreConfig(
        maturity=maturity,
        n_time_steps=n_time_steps,
        truncation_length=truncation_length,
        n_space_points=n_space_points,
        damping_alpha=damping_alpha,
    )
    inputs = CoreInputs(
        eta=lambda _t, _x: rate - 0.5 * sigma * sigma,
        sigma=lambda _t, _x: sigma,
        driver=lambda _t, _x, y, _z: -rate * y,
        terminal_condition=lambda x: max(math.exp(x) - strike, 0.0),
    )
    sol = solve_core(
        config=config,
        inputs=inputs,
        x_center=math.log(spot),
        enforce_positivity=False,
        method="new_boundary_control",
    )

    t = np.array(sol.t, dtype=float)
    x = np.array(sol.x, dtype=float)
    spots = np.exp(x)
    delta = np.array(
        [[sol.z[i][j] / (sigma * math.exp(sol.x[j])) for j in range(len(sol.x))] for i in range(len(sol.t))],
        dtype=float,
    )

    vmax = float(np.nanpercentile(np.abs(delta), 99.0))
    if not (vmax > 0.0):
        vmax = 1e-6

    _tt, ss = np.meshgrid(t, spots, indexing="ij")

    fig, ax = plt.subplots(figsize=(9.0, 5.0))
    pcm = ax.pcolormesh(
        ss,
        _tt,
        delta,
        shading="auto",
        cmap="viridis",
        vmin=-vmax,
        vmax=vmax,
    )
    ax.set_xlabel("spot S")
    ax.set_ylabel("time t")
    ax.set_title("Call delta surface (CFFT-BSDE, new boundary control) — replication-style")
    fig.colorbar(pcm, ax=ax, label="delta ≈ Z / (σ S)")
    fig.tight_layout()
    fig.savefig(outfile, dpi=150)
    plt.close(fig)


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="python -m bsde_cfft_app.plot_paper_figures",
        description="Generate paper-style PNG figures into implementation_version_0/results/ by default.",
    )
    parser.add_argument(
        "--surface-csv",
        type=Path,
        default=RESULTS_DIR / "numerical_results_surface_quick.csv",
        help="Full-spot benchmark CSV (from --benchmark-full-surface)",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=RESULTS_DIR,
        help="Directory for PNG outputs",
    )
    parser.add_argument("--spot", type=float, default=100.0)
    parser.add_argument("--strike", type=float, default=100.0)
    parser.add_argument("--rate", type=float, default=0.01)
    parser.add_argument("--sigma", type=float, default=0.2)
    parser.add_argument("--maturity", type=float, default=1.0)
    parser.add_argument("--n-time-steps", type=int, default=64)
    parser.add_argument("--truncation-length", type=float, default=10.0)
    parser.add_argument("--n-space-points", type=int, default=128)
    parser.add_argument("--alpha", type=float, default=-1.5, help="Damping alpha (<0)")
    return parser


def main(argv: list[str] | None = None) -> None:
    try:
        import matplotlib  # noqa: F401
    except ImportError as exc:  # pragma: no cover
        print(
            "matplotlib is required. Install with:\n"
            "  python -m pip install matplotlib\n"
            "or: python -m pip install -e \".[plot]\"",
            file=sys.stderr,
        )
        raise SystemExit(1) from exc

    args = _build_parser().parse_args(argv)
    surface_path: Path = args.surface_csv
    out_dir: Path = args.output_dir
    out_dir.mkdir(parents=True, exist_ok=True)

    if not surface_path.is_file():
        print(f"Surface CSV not found: {surface_path}", file=sys.stderr)
        raise SystemExit(1)

    by_method = _load_surface_rows(surface_path)

    legacy_key = "legacy_hyndman_2017"
    new_key = "new_boundary_control"

    if legacy_key in by_method:
        _plot_price_delta_vs_spot(
            rows=by_method[legacy_key],
            title="Figure 1 (replication): call price & delta errors — legacy Hyndman & Oyono Ngou (2017) style",
            outfile=out_dir / "figure_01_legacy_price_delta_errors.png",
        )
    else:
        print(f"Warning: no rows for method {legacy_key!r} in {surface_path}", file=sys.stderr)

    if new_key in by_method:
        _plot_price_delta_vs_spot(
            rows=by_method[new_key],
            title="Figure 2 (replication): call price & delta errors — new boundary control",
            outfile=out_dir / "figure_02_new_boundary_price_delta_errors.png",
        )
    else:
        print(f"Warning: no rows for method {new_key!r} in {surface_path}", file=sys.stderr)

    _plot_delta_surface(
        outfile=out_dir / "figure_03_new_boundary_delta_surface.png",
        spot=args.spot,
        strike=args.strike,
        rate=args.rate,
        sigma=args.sigma,
        maturity=args.maturity,
        n_time_steps=args.n_time_steps,
        truncation_length=args.truncation_length,
        n_space_points=args.n_space_points,
        damping_alpha=args.alpha,
    )

    print(
        "Wrote:\n"
        f"  {out_dir / 'figure_01_legacy_price_delta_errors.png'}\n"
        f"  {out_dir / 'figure_02_new_boundary_price_delta_errors.png'}\n"
        f"  {out_dir / 'figure_03_new_boundary_delta_surface.png'}"
    )


if __name__ == "__main__":
    main()
